name: GIBDD-CI-Pipeline
env:
  EB_PACKAGE_S3_BUCKET_NAME: "gibdd-stats"
  EB_APPLICATION_NAME      : "gibdd-stats"
  EB_ENVIRONMENT_NAME      : "GibddStats-env"
  DEPLOY_PACKAGE_NAME      : "gibdd-app-${{ github.sha }}.zip"
  AWS_REGION_NAME          : "eu-west-2"

  
on:
  push:
    branches: [ master ]

jobs:
  Build_and_copy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Create ZIP
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

    - name: Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}
        
    - name: Copy package to AWS-S3-bucket
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: Finish message
      run: echo "Package has been uploaded to S3."
      
  Delivery:
    runs-on: ubuntu-latest
    needs: [Build_and_copy]
    
    steps:

    - name: Create EB App
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}
        
    - name: Create App Version
      run: aws elasticbeanstalk create-application-version --application-name ${{ env.EB_APPLICATION_NAME }} --version-label "${{ github.sha }}" --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" --auto-create-application --region ${{ env.AWS_REGION_NAME }}

    - name: Deploy ElastikBeanstalk
      run: aws elasticbeanstalk update-environment --application-name ${{ env.EB_APPLICATION_NAME }} --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label ${{ github.sha }}
        
    - name: Finish Deploy message
      run: echo "Package has been deployed to EB."
